# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_showindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpage',
            name='accent_color',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
