# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_showpage_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpage',
            name='social_facebook_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showpage',
            name='social_twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
