# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20160416_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('hour', models.SmallIntegerField()),
                ('minutes', models.SmallIntegerField(choices=[(0, '0'), (1, '15'), (2, '30'), (3, '45')])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shows.ShowPage')),
            ],
        ),
    ]
