# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSlot',
            fields=[
                ('slot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shows.Slot')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shows.ShowPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('shows.slot', models.Model),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='show',
        ),
    ]
