# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20160416_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showslot',
            options={},
        ),
        migrations.RemoveField(
            model_name='showslot',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='slot',
            name='length',
            field=models.SmallIntegerField(choices=[(0, '15 mins'), (1, '30 mins'), (2, '45 mins'), (3, '1 hour'), (4, '90 mins'), (5, '2 hours')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='hour',
            field=models.SmallIntegerField(choices=[(0, '0am'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '0pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')]),
        ),
    ]
