# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('shows', '0009_remove_showepisodepage_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowEpisodeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Show Episode Listings',
            },
            bases=('wagtailcore.page',),
        ),
    ]
