# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_showcontentpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showpage',
            old_name='social_facebook_handle',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='showpage',
            old_name='social_twitter_handle',
            new_name='twitter_handle',
        ),
    ]
