# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20160418_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showaudioseriesepisodepage',
            options={'verbose_name': 'Show Audio Series Episode'},
        ),
        migrations.AddField(
            model_name='showaudioseriesindexpage',
            name='is_podcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
