# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_auto_20160419_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpage',
            name='about_content',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())), default=[]),
            preserve_default=False,
        ),
    ]
