# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_showpage_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpage',
            name='description',
            field=models.CharField(help_text='Describe the show in a tweet (140 characters)', max_length=140),
        ),
        migrations.AlterField(
            model_name='slot',
            name='hour',
            field=models.SmallIntegerField(choices=[(0, '12 midnight'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')]),
        ),
    ]
