# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_auto_20160419_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='length',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='minutes',
        ),
        migrations.AddField(
            model_name='slot',
            name='from_time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 25, 13, 5, 42, 912846, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='to_time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 25, 13, 5, 51, 505464, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
