# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_showsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showpage',
            old_name='facebook_url',
            new_name='social_facebook_url',
        ),
        migrations.RenameField(
            model_name='showpage',
            old_name='twitter_handle',
            new_name='social_mixcloud_handle',
        ),
        migrations.AddField(
            model_name='showpage',
            name='social_soundcloud_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showpage',
            name='social_twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showpage',
            name='social_youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
