# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_auto_20160602_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showslot',
            options={'verbose_name': 'Slot'},
        ),
        migrations.AddField(
            model_name='showpage',
            name='feature_interaction',
            field=models.BooleanField(default=False, verbose_name='Interaction'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Accent color'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='social_facebook_url',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='social_mixcloud_handle',
            field=models.TextField(blank=True, null=True, verbose_name='Mixcloud handle'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='social_soundcloud_handle',
            field=models.TextField(blank=True, null=True, verbose_name='Soundcloud handle'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='social_twitter_handle',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='social_youtube_url',
            field=models.TextField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='from_time',
            field=models.TimeField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='to_time',
            field=models.TimeField(verbose_name='To'),
        ),
    ]
