# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('shows', '0020_auto_20160602_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='showpage',
            name='feature_interaction',
            field=models.BooleanField(default=False, help_text='Interaction promotes the URF Text number and @urfstudio in the Player.', verbose_name='Interaction'),
        ),
    ]
