# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', models.CharField(help_text='Page content', max_length=140)),
            ],
            options={
                'verbose_name': 'Content Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
