# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 14:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccontentpage',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
