# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 19:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160529_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusettings',
            name='footer_one_menu',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_one_menu', to='server.Menu'),
        ),
        migrations.AddField(
            model_name='menusettings',
            name='footer_two_menu',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_two_menu', to='server.Menu'),
        ),
        migrations.AlterField(
            model_name='menusettings',
            name='header_menu',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_menu', to='server.Menu'),
        ),
    ]
