# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0004_auto_20160417_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
