# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepageslider_link_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='copy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
