# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='teammemberplacement',
            name='team_member',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='team.TeamPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='TeamMemberPlacement',
        ),
    ]
