# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 18:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160529_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='team.TeamPage'),
        ),
    ]
