# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_POST', 'New Post'), ('NEW_EPISODE', 'New Episode')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_actors', to='wagtailcore.Page')),
                ('prop', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_props', to='wagtailcore.Page')),
            ],
        ),
    ]
